import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css"; 
import HeaderLayout from "@/components/HeaderLayout";
import FooterLayout from "@/components/FooterLayout"; 
import NextTopLoader from 'nextjs-toploader';

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "NUSIFAT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}> 
        <NextTopLoader  color="#E90000" />
        <HeaderLayout />
        {children}
        <FooterLayout />
      </body>
    </html>
  );
}
